name: 1-exe

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - run: exe ./1.exe
   
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@master
      with:
          # 这些是发送邮件需要配置的参数，更多详细的说明请访问具体的仓库
        server_address: smtp.163.com
        server_port: 465
          # 这些sectret的环境变量需要配置在setting中的secret下
        username: ${{ secrets.EMAILNAME }}
        password: ${{ secrets.EMAILPOP }}
        subject: 知乎热搜
        body: file://mydata.html
        to: 1564356842@qq.com
        from: GitHub Actions
        content_type: text/html
