name: ceshi tiwen

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run:  python  pip install requests
            python  pip install lxml
            python  pip install email.mime.text
            python  pip install email.header
           
            python ./tiwen.py

