name: XMU AutoSignIn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 11,12 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install lxml
    - name: SignIn
      run: |
        sudo cp -p ./chromedriver /usr/bin
        chmod -R 777 /usr/bin/chromedriver
        python ./tiwen.py
     
