name: XMU AutoSignIn

on:
  push:
  
  schedule:
    - cron: '0 3,4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install lxml
    - name: SignIn
      run: |
       
        python ./tiwen.py
     
