name: auto tiwen

on:
  schedule:
    - cron: '0 3,4 * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: python ./AutoSignIn.py

     
